# Generated by Django 4.2.16 on 2024-09-20 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_match_teams_delete_teacher_match_team1_match_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='teams.teams'),
        ),
        migrations.AddField(
            model_name='teams',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
