# Generated by Django 4.2.16 on 2024-09-20 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_match_winner_teams_draw_teams_games_teams_goals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='points',
            new_name='score',
        ),
    ]
